# reusable workflow
name: Build

on:
  workflow_call:
#    inputs:
#      go-version:
#        required: true
#        type: string
#      go-arch:
#        required: true
#        type: string
#      filename:
#        required: true
#        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # without that 'git describe --tags' may result
          # in 'fatal: No names found, cannot describe anything.'
          # see https://stackoverflow.com/a/71721059/2726733
          fetch-depth: 0

      - name: Install and Build
        run: |
          npm install
          npm run build

#      - name: Create SHA256 Checksum
#        run: sha256sum ./bin/${{ env.BINARY_NAME }} > ./bin/sha256sum.txt || exit $?

#      - name: Upload binary
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.BINARY_NAME }}
#          path: ./bin/*
