# reusable workflow
name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run build
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # without that 'git describe --tags' may result
          # in 'fatal: No names found, cannot describe anything.'
          # see https://stackoverflow.com/a/71721059/2726733
          fetch-depth: 0

      - name: Install
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Prepare bin directory
        run: mkdir -p ./bin

      - name: Package build
        run: tar -czvf ./bin/build.tar.gz ./public

      - name: Create SHA256 Checksum
        run: sha256sum ./bin/build.tar.gz > ./bin/sha256sum.txt || exit $?

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./bin/*
