# reusable workflow
name: Create Github Release

on:
  workflow_call:
#    inputs:
#      binary:
#        type: string
#        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: build.tar.gz
          path: ./download

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: download/build.tar.gz
          prerelease: ${{ contains(github.ref, '-rc.') }}
