name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  version:
    name: Extract Version
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

  release:
    name: Github Release
    needs: [build, version]
    uses: ./.github/workflows/github-release.yml

  aur:
    name: Publish to AUR
    needs: [build, version, release]
    uses: ./.github/workflows/aur-release.yml
    with:
      version: ${{ needs.version.outputs.tag }}
    secrets:
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
      AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
      AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}

  # TODO: Debian package
  # package-deb:
  #   needs: build

